name: SonarQube Upload

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env: 
        SONAR_HOST_URL: https://oitilo.us.es/sonar
        SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=gii-is-psg2_psg2-2324-g4-44
          -Dsonar.host.url=https://oitilo.us.es/sonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
